Create table Customers(
  customer_id INT PRIMARY KEY AUTO_INCREMENT,
  First_name VARCHAR(100) NOT NULL ,
  Last_name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Phone INT(10) NOT NULL,
  Address VARCHAR(255)
  );
--Example values inserted.
INSERT INTO CUSTOMERS VALUES
  ('13','ABBIE','LABERT','ADDIE@GMAIL.COM','1234567891','23,STAFFORD');
UPDATE CUSTOMERS SET EMAIL="ABBIE@GMAIL.COM" WHERE EMAIL="ADDIE@GMAIL.COM"; 
SELECT * FROM CUSTOMERS;

